### ISSUE TITLE
How to disallow tags

### ISSUE THREAD

**Issue by dstollie** [cristo-rabani/meteor-universe-html-purifier#1]
I can't find a way to disallow certain tags. Can somebody tell?

**Comment by cristo-rabani** [comment]
withoutTags - An array of skipped tags, (which were before added, including defaults).

example:

```
UniHTML.purify('<p><b>Some</b> Text</p>', {withoutTags: [ 'p', 'img']});
```

**Comment by dstollie** [comment]
thanks! Will try tomorrow

**Comment by dstollie** [comment]
Hey @cristo-rabani .. I created a simple method which enables you to just set the tags and attributes you want to allow instead of the tags you don't want to add. Here's the gist:

https://gist.github.com/dstollie/ef8131cbfac2600441a0

**Comment by cristo-rabani** [comment]
+1

I can add this link to readme.md if you want.

**Comment by dstollie** [comment]
Yeah sure,  It might be helpful for others
