### ISSUE TITLE
Angular Meteor

### ISSUE THREAD

**Issue by klynicol** [cristo-rabani/meteor-universe-html-purifier#16]
Where can I import UniHTML from to use with angular2?

import { UniHTML } from "??";

**Comment by cristo-rabani** [comment]
From "meteor/vazco:universe-html-purifier"

**Comment by klynicol** [comment]
Still says cannot find module. It's listed in my packages, do I have to define a module under the typings.d.ts?

**Comment by klynicol** [comment]
^^ Thanks it works just fine, working on making a declaration for Typescript, I will post the code here when I'm finished.

**Comment by klynicol** [comment]
Typings code:
```
declare module "meteor/vazco:universe-html-purifier" {
    export module UniHTML {
      function purify (html: any, settings?: any): any;
      function setNewAllowedAttributes (attributesArray?: any, tag?: any);
      function addNewAllowedTag (tagName: any, isSelfClosing: any);
    }
}
```
