### ISSUE TITLE
Disallow every tag

### ISSUE THREAD

**Issue by jeanmichelcote** [cristo-rabani/meteor-universe-html-purifier#3]
Hi, sorry if i'm missing something obvious but is there an easy and simple way to just bulk disallow every single element AND attributes there is? Is there a way to simply output totally cleaned string with only raw text and no tag whatsoever without having to specify each tag to disallow one by one?

**Comment by cristo-rabani** [comment]
You can clean up all tags using regex:

```
var s = '<div>Ala has a cat</div><img/><p> and cat has Ala</p>'
console.log(s.replace(/<[^>]+>/g, ''));

output: 'Ala has a cat and cat has Ala'
```

This package is dedicated to situation when you want some tags but just some not all.
And to disallow default tags (including those added by method setNewAllowedAttributes ), you can use option 'withoutTags' for purify method.

But if you really need to use purify, you can make something like that:

```
var without = [
           'b','i','strong','em','blockquote','ol','ul','li',
           'h1','h2','h3','h4','h5','h6','h7',
           'p','span','pre','a','u','img','br','table' 
];

UniHTML.purify('<p><b>Some</b> Text</p><img src="pic.jpg">', {withoutTags: without});

```

**Comment by dstollie** [comment]
Or you can use this function:
https://gist.github.com/dstollie/ef8131cbfac2600441a0

and call it like:

```
UniHTML.purify('<p><b>Some</b> Text</p><img src="pic.jpg">', []);
```
