### ISSUE TITLE
Set the website of this GitHub repo to the Atmopshere package

### ISSUE THREAD

**Issue by dandv** [cristo-rabani/meteor-universe-html-purifier#5]
Example:

[![Adding GitHub repo URL](https://cloud.githubusercontent.com/assets/33569/6536430/76a7d88e-c402-11e4-8883-6ab2c7b8c30a.png)](https://github.com/dandv/meteor-webix)

**Comment by cristo-rabani** [comment]
Hello Dandv,

Why I should make advertisement of atmospherejs.com on github?

There are other web interfaces for troposphere catalog 
What with them? for example a fastosphere.meteor.com?

**Comment by dandv** [comment]
Any of them would do. This is optional, of course. Most Meteor packages do set their repo website to Atmosphere, because it shows the number of downloads, stars, trends etc.

**Comment by cristo-rabani** [comment]
ok I added link
