### ISSUE TITLE
Comparison with sanitize-html

### ISSUE THREAD

**Issue by dandv** [cristo-rabani/meteor-universe-html-purifier#7]
While searching for [HTML sanitization packages on Atmosphere](https://atmospherejs.com/?q=sanitize), I found [this package](https://atmospherejs.com/vazco/universe-html-purifier) and a wrapper package around @punkave's very popular [sanitize-html](https://www.npmjs.com/package/sanitize-html).

Since sanitization is tricky and the risks are important, I was wondering how this package compares to prior art, and what the rationale was when creating it.

**Comment by steph643** [comment]
My 2c:
- vazco:universe-html-purifier and cristo-rabani/meteor-universe-html-purifier are the same package
- sanitize-html is a nodejs module, so available wrappers are server-side only. Since html sanitization is usually a client-side task, there is no other choice but to use the present package.

**Comment by dandv** [comment]
> html sanitization is usually a client-side task

I'd rather do sanitization on the server:
- for security, because if you have any HTML input, e.g. a WYSIWYG editor, an attacker could always send HTML with scripting inside
- for performance, to store the sanitized version in the database, and get rid of cruft and attacks
- for client-side performance, to avoid sanitizing every time the same malicious HTML would otherwise be sent to the client

You could sanitize on the client too before persisting (as a form of [optimistic UI](http://info.meteor.com/blog/optimistic-ui-with-meteor-latency-compensation)).

**Comment by steph643** [comment]
@dandv, I have to disagree. See for example the accepted answer here:
http://stackoverflow.com/questions/23839173/how-safe-is-client-side-html-sanitization

**Comment by cristo-rabani** [comment]
Hello,

If keeping in db original source of content _(potentially with js)_ is acceptable for you
You can purifying such data just before adding to the dom. For example it can be helper in template 

```
{{{purify untrustHtml}}}
```

Even if someone inject somehow script to the value
Displaying of this content will be safely for other users.
- **the advantage** of this solution:
  -  Saving server resources
  -  We have originally data source
- **the disadvantage**
  - We must purify always before such content will be loaded. 
  - We cannot forget about this operation in other places.

But if you want have safely of html content in database or you don't want to do that any time before content will be loaded.

Is only one way,
You should purify data before saving it in db, on server side or both sides.
_( I seen that some developers make the purifying in autovalue method in SimpleSchema, or even as a validator )_
