### ISSUE TITLE
Unwanted <p> tags

### ISSUE THREAD

**Issue by Volodymyr-K** [cristo-rabani/meteor-universe-html-purifier#9]
When I run `UniHTML.purify('text \n text2')` I get "text text2", but when I run `UniHTML.purify('text \n\n text2')` I get this instead:

```
<p>
    text 
</p>
<p>
    text2
</p>
```

Is this a bug? How can I keep both \n and avoid the `<p>` tags?

**Comment by cristo-rabani** [comment]
Hello,
Sorry for long time to respond.

Pass flag "noTextManhandle : true" in options.
This should skip a text processing like clearing whitespace including `\n`
